sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t mvcaaa/rpi-mysql .
# test image
- docker run mvcaaa/rpi-mysql mysql --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag mvcaaa/rpi-mysql mvcaaa/rpi-mysql:$TAG
    docker push mvcaaa/rpi-mysql:$TAG
    docker push mvcaaa/rpi-mysql
  fi
